### ISSUE TITLE
Config with a separate /content/ folder

### ISSUE THREAD

**Issue by fredl99** [netzzwerg/ghost-helper-toc#4]
Hi,
In my setup the `content` folder is separated from the main folder, so I cannot use a path like `./content/themes/yourtheme/toc`. 

Can someone with more JavaScript knowledge help me here? Ideally I'd like to work with a variable like `ContentPath`, which is set in config.js.

And:
I dont't know if that's a related problem, but the whole thing doesn't work with ghost 0.7.11, even if I set the complete filesystem path in index.js.
The error is: `Error: Cannot find module 'express-hbs'`

Any help would be appreciated, thanks!
